baseurl = "/"
languageCode = "en-us"
theme = "hugo-goa"
title = "PDX Go"

[params]
    authorimage = "pdxgopher.svg"
    dateformat = "2006-01-02"
    description = "Portland's Go programming language user group"
    highlightjs = true
    highlightjsstyle = "darcula"
    postNavigation = false
    
[params.extra]
    poweredby = true
    
[permalinks]
  post = "/:year/:month/:slug/"

[menu]

[[menu.main]]
  name = "Our meetup dates"
  weight = 10
  url = "/meetups"

[[menu.main]]
  name = "About our meetup"
  weight = 20
  url = "/about"