baseurl = "http://pdxgo.org"
languageCode = "en-us"
Title = "PDXGo"

Description = "Eh?"

[params]
Title = "WatGO"
Description = "Golang enthusiast group for Portland! Gophers of all experience levels welcome!"

[Site]
Title = "HuhGo"
