baseurl = "http://pdxgo.org"
languageCode = "en-us"
theme = "hugo-goa"
title = "PDX Go"

[params]
    authorimage = "pdxgopher.svg"
    dateformat = "2006-01-02"
    description = "Portland's Go programming language user group"
    highlightjs = true
    highlightjsstyle = "darcula"
    postNavigation = false
    
[permalinks]
  post = "/:year/:month/:slug/"

## Main Menu
[menu]

[[menu.main]]
    name = "Posts"
    weight = 10
    url = "post/"

[[menu.main]]
    name = "About"
    weight = 20
    url = "/about/"